language: objective-c
before_install:
- gem install cocoapods --no-document
- gem install xcpretty --no-document
script:
- set -o pipefail
- xcodebuild -workspace JWT.xcworkspace -scheme JWT test -sdk macosx | xcpretty -c
- pod lib lint
